import type { Metadata } from "next";
import "./globals.css";
import LoginButton from "@/components/LoginButton";
import UserData from "@/components/UserData";
import { AppThemeProvider } from "@/providers/ThemeProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import AppContainer from "@/components/ui/layout/container";
import { inter, roboto } from "@/theme/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${inter.variable} ${roboto.variable} h-full antialiased`}
		>
			<body>
				<AppRouterCacheProvider>
					<header className="flex items-center justify-center gap-2 py-8 bg-zinc-50 font-sans dark:bg-black">
						<UserData />
						<LoginButton />
					</header>
					<AppThemeProvider>
						<AppContainer>{children}</AppContainer>
					</AppThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
