// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ApiBlockGridAreaModel = {
    alias: string;
    rowSpan: number;
    columnSpan: number;
    items: Array<ApiBlockGridItemModel>;
};

export type ApiBlockGridItemModel = ApiBlockItemModel & {
    rowSpan?: number;
    columnSpan?: number;
    areaGridColumns?: number;
    areas?: Array<ApiBlockGridAreaModel>;
};

export type ApiBlockGridModel = {
    gridColumns: number;
    items: Array<ApiBlockGridItemModel>;
};

export type ApiBlockItemModel = {
    content: IApiElementModel;
    settings?: IApiElementModel;
};

export type ApiContentRouteModel = {
    path: string;
    queryString?: string | null;
    startItem: ApiContentStartItemModel;
};

export type ApiContentStartItemModel = {
    id: string;
    path: string;
};

export type ApiLinkModel = {
    readonly url?: string | null;
    readonly queryString?: string | null;
    readonly title?: string | null;
    readonly target?: string | null;
    readonly destinationId?: string | null;
    readonly destinationType?: string | null;
    route?: ApiContentRouteModel | null;
    linkType: LinkTypeModel;
    readonly culture?: string | null;
};

export type ContentPageContentModel = Omit<IApiContentModelBase, 'contentType'> & {
    contentType: 'contentPage';
} & {
    properties?: ContentPagePropertiesModel;
};

export type ContentPageContentResponseModel = Omit<IApiContentResponseModelBase, 'contentType'> & Omit<ContentPageContentModel, 'contentType'> & {
    contentType: 'contentPage';
};

export type ContentPagePropertiesModel = MetadataAndNavigationPropertiesModel & {
    body?: ApiBlockGridModel;
};

export type HomePageContentModel = Omit<IApiContentModelBase, 'contentType'> & {
    contentType: 'homePage';
} & {
    properties?: HomePagePropertiesModel;
};

export type HomePageContentResponseModel = Omit<IApiContentResponseModelBase, 'contentType'> & Omit<HomePageContentModel, 'contentType'> & {
    contentType: 'homePage';
};

export type HomePagePropertiesModel = MetadataAndNavigationPropertiesModel & {
    body?: ApiBlockGridModel;
    logo?: Array<IApiMediaWithCropsModel> | null;
    headerContent?: RichTextGenericElementModel | RichTextRootElementModel | RichTextTextElementModel;
    footerContent?: RichTextGenericElementModel | RichTextRootElementModel | RichTextTextElementModel;
    links?: Array<ApiLinkModel> | null;
    copyrightText?: string | null;
    gtmContainerId?: string | null;
    searchResultsPage?: Array<IApiContentModel> | null;
    robotsTxt?: string | null;
};

export type HttpValidationProblemDetails = ProblemDetails & {
    errors?: {
        [key: string]: Array<string>;
    };
    [key: string]: unknown;
};

export type IApiContentModel = ContentPageContentModel | HomePageContentModel;

export type IApiContentModelBase = Omit<IApiElementModelBase, 'contentType'> & {
    contentType: 'IApiContentModelBase';
} & {
    readonly id: string;
    readonly contentType: string;
    readonly name?: string | null;
    readonly createDate: string;
    readonly updateDate: string;
    route: ApiContentRouteModel;
};

export type IApiContentResponseModel = ContentPageContentResponseModel | HomePageContentResponseModel;

export type IApiContentResponseModelBase = Omit<IApiContentModelBase, 'contentType'> & {
    contentType: 'IApiContentResponseModelBase';
} & {
    readonly id: string;
    readonly contentType: string;
    readonly name?: string | null;
    readonly createDate: string;
    readonly updateDate: string;
    route: ApiContentRouteModel;
    readonly cultures: {
        [key: string]: ApiContentRouteModel;
    };
};

export type IApiElementModel = MetadataAndNavigationElementModel;

export type IApiElementModelBase = {
    readonly id: string;
    readonly contentType: string;
};

export type IApiMediaWithCropsModel = {
    readonly id: string;
    readonly name: string;
    readonly mediaType: string;
    readonly url: string;
    readonly extension?: string | null;
    readonly width?: number | null;
    readonly height?: number | null;
    readonly bytes?: number | null;
    readonly properties: {
        [key: string]: unknown;
    };
    focalPoint?: ImageFocalPointModel;
    readonly crops?: Array<ImageCropModel> | null;
};

export type IApiMediaWithCropsResponseModel = {
    readonly id: string;
    readonly name: string;
    readonly mediaType: string;
    readonly url: string;
    readonly extension?: string | null;
    readonly width?: number | null;
    readonly height?: number | null;
    readonly bytes?: number | null;
    readonly properties: {
        [key: string]: unknown;
    };
    focalPoint: ImageFocalPointModel;
    readonly crops?: Array<ImageCropModel> | null;
    readonly path: string;
    readonly createDate: string;
    readonly updateDate: string;
};

export type ImageCropCoordinatesModel = {
    x1: number;
    y1: number;
    x2: number;
    y2: number;
};

export type ImageCropModel = {
    alias?: string | null;
    width: number;
    height: number;
    coordinates?: ImageCropCoordinatesModel;
};

export type ImageFocalPointModel = {
    left: number;
    top: number;
};

export type LinkTypeModel = 'Content' | 'Media' | 'External';

export type MetadataAndNavigationElementModel = Omit<IApiElementModelBase, 'contentType'> & {
    contentType: 'metadataAndNavigation';
} & {
    properties?: MetadataAndNavigationPropertiesModel;
};

export type MetadataAndNavigationPropertiesModel = {
    metaTitle?: string | null;
    metaDescription?: string | null;
    structuredData?: string | null;
    displayName?: string | null;
    excludeFromSearch?: boolean | null;
    excludeFromSitemap?: boolean | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
    umbracoUrlName?: string | null;
    umbracoUrlAliases?: string | null;
};

export type PagedIApiContentResponseModel = {
    total: number;
    items: Array<IApiContentResponseModel>;
};

export type PagedIApiMediaWithCropsResponseModel = {
    total: number;
    items: Array<IApiMediaWithCropsResponseModel>;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type RichTextGenericElementModel = {
    tag: string;
    attributes: {
        [key: string]: unknown;
    };
    elements: Array<RichTextGenericElementModel | RichTextRootElementModel | RichTextTextElementModel>;
};

export type RichTextRootElementModel = {
    readonly tag: string;
    attributes: {
        [key: string]: unknown;
    };
    elements: Array<RichTextGenericElementModel | RichTextRootElementModel | RichTextTextElementModel>;
    blocks: Array<ApiBlockItemModel | ApiBlockGridItemModel>;
};

export type RichTextTextElementModel = {
    text: string;
    readonly tag: string;
};

export type ApiBlockGridAreaModelWritable = {
    alias: string;
    rowSpan: number;
    columnSpan: number;
    items: Array<ApiBlockGridItemModelWritable>;
};

export type ApiBlockGridItemModelWritable = ApiBlockItemModelWritable & {
    rowSpan?: number;
    columnSpan?: number;
    areaGridColumns?: number;
    areas?: Array<ApiBlockGridAreaModelWritable>;
};

export type ApiBlockGridModelWritable = {
    gridColumns: number;
    items: Array<ApiBlockGridItemModelWritable>;
};

export type ApiBlockItemModelWritable = {
    content: IApiElementModelWritable;
    settings?: IApiElementModelWritable;
};

export type ApiLinkModelWritable = {
    linkType: LinkTypeModel;
};

export type ContentPageContentModelWritable = Omit<IApiContentModelBaseWritable2, 'contentType'> & {
    contentType: 'contentPage';
} & {
    properties?: ContentPagePropertiesModelWritable;
};

export type ContentPageContentResponseModelWritable = Omit<IApiContentResponseModelBaseWritable2, 'contentType'> & Omit<ContentPageContentModelWritable, 'contentType'> & {
    contentType: 'contentPage';
};

export type ContentPagePropertiesModelWritable = MetadataAndNavigationPropertiesModel & {
    body?: ApiBlockGridModelWritable;
};

export type HomePageContentModelWritable = Omit<IApiContentModelBaseWritable2, 'contentType'> & {
    contentType: 'homePage';
} & {
    properties?: HomePagePropertiesModelWritable;
};

export type HomePageContentResponseModelWritable = Omit<IApiContentResponseModelBaseWritable2, 'contentType'> & Omit<HomePageContentModelWritable, 'contentType'> & {
    contentType: 'homePage';
};

export type HomePagePropertiesModelWritable = MetadataAndNavigationPropertiesModel & {
    body?: ApiBlockGridModelWritable;
    logo?: Array<IApiMediaWithCropsModelWritable> | null;
    headerContent?: RichTextGenericElementModelWritable | RichTextRootElementModelWritable | RichTextTextElementModelWritable;
    footerContent?: RichTextGenericElementModelWritable | RichTextRootElementModelWritable | RichTextTextElementModelWritable;
    links?: Array<ApiLinkModelWritable> | null;
    copyrightText?: string | null;
    gtmContainerId?: string | null;
    searchResultsPage?: Array<IApiContentModelWritable> | null;
    robotsTxt?: string | null;
};

export type IApiContentModelWritable = ContentPageContentModelWritable | HomePageContentModelWritable;

export type IApiContentModelBaseWritable = {
    [key: string]: never;
};

export type IApiContentResponseModelWritable = ContentPageContentResponseModelWritable | HomePageContentResponseModelWritable;

export type IApiContentResponseModelBaseWritable = Omit<IApiContentModelBaseWritable2, 'contentType'> & {
    contentType: 'IApiContentResponseModelBaseWritable';
};

export type IApiElementModelWritable = MetadataAndNavigationElementModelWritable;

export type IApiMediaWithCropsModelWritable = {
    focalPoint?: ImageFocalPointModel;
};

export type IApiMediaWithCropsResponseModelWritable = {
    focalPoint: ImageFocalPointModel;
};

export type MetadataAndNavigationElementModelWritable = {
    properties?: MetadataAndNavigationPropertiesModel;
};

export type PagedIApiContentResponseModelWritable = {
    total: number;
    items: Array<IApiContentResponseModelWritable>;
};

export type PagedIApiMediaWithCropsResponseModelWritable = {
    total: number;
    items: Array<IApiMediaWithCropsResponseModelWritable>;
};

export type RichTextGenericElementModelWritable = {
    tag: string;
    attributes: {
        [key: string]: unknown;
    };
    elements: Array<RichTextGenericElementModelWritable | RichTextRootElementModelWritable | RichTextTextElementModelWritable>;
};

export type RichTextRootElementModelWritable = {
    attributes: {
        [key: string]: unknown;
    };
    elements: Array<RichTextGenericElementModelWritable | RichTextRootElementModelWritable | RichTextTextElementModelWritable>;
    blocks: Array<ApiBlockItemModelWritable | ApiBlockGridItemModelWritable>;
};

export type RichTextTextElementModelWritable = {
    text: string;
};

export type IApiContentModelBaseWritable2 = Omit<IApiElementModelBase, 'contentType'> & {
    contentType: 'IApiContentModelBaseWritable2';
} & {
    readonly id: string;
    readonly contentType: string;
    readonly name?: string | null;
    readonly createDate: string;
    readonly updateDate: string;
    route: ApiContentRouteModel;
};

export type IApiContentResponseModelBaseWritable2 = Omit<IApiContentModelBase, 'contentType'> & {
    contentType: 'IApiContentResponseModelBaseWritable2';
} & {
    readonly id: string;
    readonly contentType: string;
    readonly name?: string | null;
    readonly createDate: string;
    readonly updateDate: string;
    route: ApiContentRouteModel;
    readonly cultures: {
        [key: string]: ApiContentRouteModel;
    };
};

export type GetContent20Data = {
    body?: never;
    headers?: {
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Defines the segment to return. Use this when querying segment variant content items.
         */
        'Accept-Segment'?: string;
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
        /**
         * Whether to request draft content.
         */
        Preview?: boolean;
        /**
         * URL segment or GUID of a root content item.
         */
        'Start-Item'?: string;
    };
    path?: never;
    query?: {
        /**
         * Specifies the content items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fetch?: string;
        /**
         * Defines how to filter the fetched content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        filter?: Array<string>;
        /**
         * Defines how to sort the found content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        sort?: Array<string>;
        /**
         * Specifies the number of found content items to skip. Use this to control pagination of the response.
         */
        skip?: number;
        /**
         * Specifies the number of found content items to take. Use this to control pagination of the response.
         */
        take?: number;
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/content';
};

export type GetContent20Errors = {
    /**
     * Bad Request
     */
    400: ProblemDetails | HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetContent20Error = GetContent20Errors[keyof GetContent20Errors];

export type GetContent20Responses = {
    /**
     * OK
     */
    200: PagedIApiContentResponseModel;
};

export type GetContent20Response = GetContent20Responses[keyof GetContent20Responses];

export type GetContentItemByPath20Data = {
    body?: never;
    headers?: {
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Defines the segment to return. Use this when querying segment variant content items.
         */
        'Accept-Segment'?: string;
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
        /**
         * Whether to request draft content.
         */
        Preview?: boolean;
        /**
         * URL segment or GUID of a root content item.
         */
        'Start-Item'?: string;
    };
    path: {
        path: string;
    };
    query?: {
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/content/item/{path}';
};

export type GetContentItemByPath20Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetContentItemByPath20Responses = {
    /**
     * OK
     */
    200: IApiContentResponseModel;
};

export type GetContentItemByPath20Response = GetContentItemByPath20Responses[keyof GetContentItemByPath20Responses];

export type GetContentItemById20Data = {
    body?: never;
    headers?: {
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Defines the segment to return. Use this when querying segment variant content items.
         */
        'Accept-Segment'?: string;
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
        /**
         * Whether to request draft content.
         */
        Preview?: boolean;
        /**
         * URL segment or GUID of a root content item.
         */
        'Start-Item'?: string;
    };
    path: {
        id: string;
    };
    query?: {
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/content/item/{id}';
};

export type GetContentItemById20Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetContentItemById20Responses = {
    /**
     * OK
     */
    200: IApiContentResponseModel;
};

export type GetContentItemById20Response = GetContentItemById20Responses[keyof GetContentItemById20Responses];

export type GetContentItems20Data = {
    body?: never;
    headers?: {
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Defines the segment to return. Use this when querying segment variant content items.
         */
        'Accept-Segment'?: string;
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
        /**
         * Whether to request draft content.
         */
        Preview?: boolean;
        /**
         * URL segment or GUID of a root content item.
         */
        'Start-Item'?: string;
    };
    path?: never;
    query?: {
        id?: Array<string>;
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/content/items';
};

export type GetContentItems20Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetContentItems20Responses = {
    /**
     * OK
     */
    200: Array<IApiContentResponseModel>;
};

export type GetContentItems20Response = GetContentItems20Responses[keyof GetContentItems20Responses];

export type GetMedia20Data = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
    };
    path?: never;
    query?: {
        /**
         * Specifies the media items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fetch?: string;
        /**
         * Defines how to filter the fetched media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        filter?: Array<string>;
        /**
         * Defines how to sort the found media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        sort?: Array<string>;
        /**
         * Specifies the number of found media items to skip. Use this to control pagination of the response.
         */
        skip?: number;
        /**
         * Specifies the number of found media items to take. Use this to control pagination of the response.
         */
        take?: number;
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/media';
};

export type GetMedia20Errors = {
    /**
     * Bad Request
     */
    400: ProblemDetails | HttpValidationProblemDetails;
};

export type GetMedia20Error = GetMedia20Errors[keyof GetMedia20Errors];

export type GetMedia20Responses = {
    /**
     * OK
     */
    200: PagedIApiMediaWithCropsResponseModel;
};

export type GetMedia20Response = GetMedia20Responses[keyof GetMedia20Responses];

export type GetMediaItemByPath20Data = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
    };
    path: {
        path: string;
    };
    query?: {
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/media/item/{path}';
};

export type GetMediaItemByPath20Errors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMediaItemByPath20Responses = {
    /**
     * OK
     */
    200: IApiMediaWithCropsResponseModel;
};

export type GetMediaItemByPath20Response = GetMediaItemByPath20Responses[keyof GetMediaItemByPath20Responses];

export type GetMediaItemById20Data = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: {
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/media/item/{id}';
};

export type GetMediaItemById20Errors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMediaItemById20Responses = {
    /**
     * OK
     */
    200: IApiMediaWithCropsResponseModel;
};

export type GetMediaItemById20Response = GetMediaItemById20Responses[keyof GetMediaItemById20Responses];

export type GetMediaItems20Data = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
    };
    path?: never;
    query?: {
        id?: Array<string>;
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/media/items';
};

export type GetMediaItems20Responses = {
    /**
     * OK
     */
    200: Array<IApiMediaWithCropsResponseModel>;
};

export type GetMediaItems20Response = GetMediaItems20Responses[keyof GetMediaItems20Responses];
